### ISSUE TITLE
Compiling error when CONFIG_SCHED_DEBUG is enabled

### ISSUE THREAD

**Issue by raykzhao** [hamadmarri/cacule-cpu-scheduler#18]
Hi @hamadmarri 

I got the following error with the latest CacULE patch when compiling with `CONFIG_SCHED_DEBUG` enabled:

```
kernel/sched/fair.c:748:9: error: incompatible pointer types returning 'struct cacule_node *' from a function with result type 'struct sched_entity *'
```

Should line 748 be `return se_of(cfs_rq->head);`?

**Comment by raykzhao** [comment]
In addition, I also got the following errors:
kernel/sched/debug.c:442:18: error: no member named 'vruntime' in 'struct sched_entity'
kernel/sched/debug.c:506:49: error: no member named 'vruntime' in 'struct sched_entity'
kernel/sched/debug.c:509:24: error: no member named 'vruntime' in 'struct sched_entity'
kernel/sched/debug.c:887:8: error: no member named 'vruntime' in 'struct sched_entity'

**Comment by hamadmarri** [comment]
Yes, you are right. I will fix that.

Thank you @raykzhao

**Comment by hamadmarri** [comment]
Hi @raykzhao 

Please check this commit: https://github.com/hamadmarri/cacule-cpu-scheduler/commit/d9cac29d56687c477e1b2b2691153d368bb2dfdc

I also fixed returning last entity instead of the first in `__pick_last_entity`

Thank you
