### ISSUE TITLE
Feature Request: Use kconfig menu to select between Cachy/CacULE

### ISSUE THREAD

**Issue by raykzhao** [hamadmarri/cacule-cpu-scheduler#19]
Hi @hamadmarri 

Since CacULE scheduler might work better on some machine/load, and Cachy might work better for the others, it probably makes sense to have a single patch and use kconfig menu to select between Cachy/CacULE, similar to how PDS/BMQ schedulers did. The source codes between Cachy/CacULE are also quite similar in my opinion, as the most noticeable difference is the scheduling policy.

**Comment by hamadmarri** [comment]
Hi @raykzhao 

It's a good idea. I am going to try to combine both in one patch with selectable options in kconfig.

Thank you

**Comment by hamadmarri** [comment]
Hi @raykzhao 

I have implemented some features that are dependent on interactive score scheme. I don't think
I am able to make such features with HRRN for Cachy. As far I know last time you were satisfied with CacULE. Please let me know if Cachy is not needed anymore.

Thank you

**Comment by raykzhao** [comment]
Hi @hamadmarri,

Yes, currently CacULE + rdb works fine for me and you may close this issue.
