### ISSUE TITLE
rdb patch

### ISSUE THREAD

**Issue by kevall474** [hamadmarri/cacule-cpu-scheduler#45]
Issue when applying rdb-5.13.patch with cacule-5.13.patch.

kevin@archlinux-portable ~/D/linux-5.13.7> patch -Np1 < ../cacule-5.13.patch
patching file Documentation/admin-guide/sysctl/kernel.rst
patching file Documentation/scheduler/sched-CacULE.rst
patching file include/linux/sched.h
patching file include/linux/sched/sysctl.h
patching file init/Kconfig
patching file kernel/Kconfig.hz
patching file kernel/sched/core.c
patching file kernel/sched/debug.c
patching file kernel/sched/fair.c
patching file kernel/sched/sched.h
patching file kernel/sysctl.c
kevin@archlinux-portable ~/D/linux-5.13.7> patch -Np1 < ../rdb-5.13.patch
patching file init/Kconfig
patching file kernel/sched/core.c
patching file kernel/sched/fair.c
Hunk #8 FAILED at 4936.
Hunk #9 succeeded at 5171 (offset -4 lines).
Hunk #10 succeeded at 5251 (offset -4 lines).
Hunk #11 succeeded at 5338 (offset -4 lines).
Hunk #12 succeeded at 5791 (offset -4 lines).
Hunk #13 succeeded at 6039 (offset -4 lines).
Hunk #14 succeeded at 6092 (offset -4 lines).
Hunk #15 succeeded at 7621 with fuzz 2 (offset -4 lines).
Hunk #16 succeeded at 7663 (offset 1 line).
Hunk #17 succeeded at 7973 (offset 1 line).
Hunk #18 succeeded at 8395 (offset 1 line).
Hunk #19 succeeded at 8445 (offset 1 line).
Hunk #20 succeeded at 8471 (offset 1 line).
Hunk #21 succeeded at 8562 (offset 1 line).
Hunk #22 succeeded at 8574 (offset 1 line).
Hunk #23 succeeded at 8582 (offset 1 line).
Hunk #24 succeeded at 8601 (offset 1 line).
Hunk #25 succeeded at 9705 (offset 1 line).
Hunk #26 succeeded at 9974 (offset 1 line).
Hunk #27 succeeded at 10011 (offset 1 line).
Hunk #28 succeeded at 10344 (offset 1 line).
Hunk #29 succeeded at 10383 (offset 1 line).
Hunk #30 succeeded at 10469 (offset 1 line).
Hunk #31 succeeded at 10480 (offset 1 line).
Hunk #32 succeeded at 10573 (offset 1 line).
Hunk #33 succeeded at 10607 (offset 1 line).
Hunk #34 succeeded at 10758 (offset 1 line).
Hunk #35 succeeded at 10879 (offset 1 line).
Hunk #36 succeeded at 10959 (offset 1 line).
Hunk #37 succeeded at 10989 (offset 1 line).
Hunk #38 succeeded at 11010 (offset 1 line).
Hunk #39 succeeded at 11060 (offset 1 line).
Hunk #40 succeeded at 11069 (offset 1 line).
Hunk #41 succeeded at 11203 (offset 1 line).
Hunk #42 succeeded at 11460 (offset 1 line).
Hunk #43 succeeded at 12308 (offset 1 line).
1 out of 43 hunks FAILED -- saving rejects to file kernel/sched/fair.c.rej
patching file kernel/sched/idle.c
patching file kernel/sched/sched.h

here the .rej file
[fair.c.rej.txt](https://github.com/hamadmarri/cacule-cpu-scheduler/files/6912906/fair.c.rej.txt)

**Comment by kevall474** [comment]
.

**Comment by hamadmarri** [comment]
Thank you so much @kevall474  for reporting this issue. I have updated RDB patch.

Thank you
